framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        message_bus: messenger.bus.default
        envelope:
            sender: '%env(EMAIL)%'
        headers:
            From: '%env(EMAIL)%'
            Reply-To: '%env(CONTACT_EMAIL)%'
