[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:symfony-server]
# user= and directory= will not work with symfony-cli development server
# as it does not set environmnet variables like HOME or USER
command=su user -lc "cd /var/www/html && symfony server:start --allow-all-ip"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0